services:
  nquant:
    build:
      context: .
      dockerfile: Dockerfile
    image: nquant

    ports:
      - "8888:8888"
    volumes:
      - type: bind
        source: .
        target: /nerdieQuant
          #      - type: bind
          #        source: .config/rstudio
          #        target: /home/rstudio/.config/rstudio
          #      - type: bind
          #        source: ~/.Renviron
          #        target: /home/rstudio/.Renviron
    environment:
      - JUPYTER_TOKEN=jupyter
    command: jupyter lab --ip 0.0.0.0  --port 8888 --no-browser --allow-root
