[project]
name = "nquant"
version = "0.1.0"
description = "Notes of quantitative investments."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "notebook",
    "numpy",
    "pandas",
    "statistics",
    "plotnine",
    "yfinance",
    "nasdaq-data-link",
    "fredapi",
]
